# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will do a clean install of dotnet dependencies

name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test on dotnet ${{ matrix.dotnet-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: ['7.0.x']
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Before Build
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Unit Test
      run: |
        dotnet test --no-build --verbosity normal src/IBM.Watson.Assistant.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.Assistant.v2/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.Discovery.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.Discovery.v2/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.LanguageTranslator.v3/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.SpeechToText.v1/Test/Unit
        dotnet test --no-build --verbosity normal src/IBM.Watson.TextToSpeech.v1/Test/Unit
